# Serena configuration for PinGlass
# AI Photo Portrait Generation Platform

project_name: "PinGlass"
encoding: "utf-8"

# Languages for semantic code analysis
languages:
  - typescript
  - javascript

# Use gitignore + additional paths to ignore
ignore_all_files_in_gitignore: true
ignored_paths:
  - .next
  - node_modules
  - .git
  - "*.lock"
  - "*.log"
  - dist
  - build
  - coverage
  - PinkGlass  # Screenshots folder

# Project settings
read_only: false
excluded_tools: []
included_optional_tools: []

# Project context for AI assistants
initial_prompt: |
  # PinGlass (AI Photo Portraits)

  ## Overview
  Next.js 16 web application for generating AI photo portraits using Google Imagen 3.0.
  Users upload 10-20 reference photos, select a pricing tier (7/15/23 photos), pay, and receive AI-generated portraits.

  ## Tech Stack
  - Frontend: React 19, Next.js 16 (App Router), TypeScript
  - Styling: Tailwind CSS 4 with OKLCH color space
  - Database: Neon PostgreSQL (serverless)
  - AI: Google Imagen 3.0 API (via YeScale proxy)
  - Payments: T-Bank (Tinkoff) Payment API

  ## Pricing Tiers
  - Starter: 7 photos - 499 RUB
  - Standard: 15 photos - 999 RUB (popular)
  - Premium: 23 photos - 1499 RUB

  ## Key Files (with line counts)
  - `components/persona-app.tsx` (414 lines) - Main component, all views and state
  - `components/payment-modal.tsx` (323 lines) - Payment UI with tier selection
  - `lib/imagen.ts` (521 lines) - Google Imagen API wrapper
  - `lib/prompts.ts` (103 lines) - 23 generation prompts + style configs
  - `lib/tbank.ts` (240 lines) - T-Bank payment integration
  - `lib/db.ts` (63 lines) - Database client and TypeScript types
  - `app/api/generate/route.ts` (264 lines) - Photo generation endpoint
  - `app/api/payment/create/route.ts` (73 lines) - Payment creation
  - `app/api/payment/status/route.ts` (88 lines) - Payment status check
  - `app/api/payment/webhook/route.ts` (58 lines) - T-Bank webhooks

  ## Component Views (in persona-app.tsx)
  - OnboardingView (lines 154-226) - Animated welcome with orbiting photos
  - DashboardView (lines 228-280) - Avatar gallery with pricing tiers
  - UploadView (lines 282-328) - Multi-file upload (10-20 photos)
  - TierSelectView (lines 331-364) - Select 7/15/23 photo package
  - GeneratingView (lines 138-152) - Progress indicator
  - ResultsView (lines 366-414) - Generated photos gallery

  ## User Flow
  1. Onboarding (animated intro) -> 2. Upload (10-20 photos)
  3. Select tier (7/15/23 photos) -> 4. Payment (T-Bank)
  5. Generation (AI photos) -> 6. Results gallery (download)

  ## Database Tables
  - users (device_id, telegram_user_id) - payment status from payments table
  - avatars (user_id, name, status, thumbnail_url)
  - generated_photos (avatar_id, style_id, prompt, image_url)
  - payments (user_id, payment_id, amount, status)
  - generation_jobs (avatar_id, style_id, status, progress)

  ## Styles (in lib/prompts.ts)
  - PinGlass: All 23 prompts, optimistic vibrant portraits
  - Professional: 9 prompts for business/LinkedIn
  - Lifestyle: 9 prompts for social media
  - Creative: 9 prompts for artistic portfolio

# Source file patterns for indexing
source_patterns:
  - "app/**/*.ts"
  - "app/**/*.tsx"
  - "components/**/*.tsx"
  - "lib/**/*.ts"
  - "styles/**/*.css"
  - "*.json"
  - "*.mjs"
  - "*.js"
  - "*.md"
