# Serena configuration for PinGlass
# AI Photo Portrait Generation Platform

project_name: "PinGlass"

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# Languages for semantic code analysis
languages:
- typescript
- typescript

# whether to use project's .gitignore files to ignore files
ignore_all_files_in_gitignore: true

# list of additional paths to ignore in all projects
# same syntax as gitignore, so you can use * and **
ignored_paths:
- .next
- node_modules
- .git
- "*.lock"
- "*.log"
- dist
- build
- coverage
- PinkGlass

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# list of tool names to exclude. We recommend not excluding any tools, see the readme for more details.
# Below is the complete list of tools for convenience.
# To make sure you have the latest list of tools, and to view their descriptions, 
# execute `uv run scripts/print_tool_overview.py`.
#
#  * `activate_project`: Activates a project by name.
#  * `check_onboarding_performed`: Checks whether project onboarding was already performed.
#  * `create_text_file`: Creates/overwrites a file in the project directory.
#  * `delete_lines`: Deletes a range of lines within a file.
#  * `delete_memory`: Deletes a memory from Serena's project-specific memory store.
#  * `execute_shell_command`: Executes a shell command.
#  * `find_referencing_code_snippets`: Finds code snippets in which the symbol at the given location is referenced.
#  * `find_referencing_symbols`: Finds symbols that reference the symbol at the given location (optionally filtered by type).
#  * `find_symbol`: Performs a global (or local) search for symbols with/containing a given name/substring (optionally filtered by type).
#  * `get_current_config`: Prints the current configuration of the agent, including the active and available projects, tools, contexts, and modes.
#  * `get_symbols_overview`: Gets an overview of the top-level symbols defined in a given file.
#  * `initial_instructions`: Gets the initial instructions for the current project.
#     Should only be used in settings where the system prompt cannot be set,
#     e.g. in clients you have no control over, like Claude Desktop.
#  * `insert_after_symbol`: Inserts content after the end of the definition of a given symbol.
#  * `insert_at_line`: Inserts content at a given line in a file.
#  * `insert_before_symbol`: Inserts content before the beginning of the definition of a given symbol.
#  * `list_dir`: Lists files and directories in the given directory (optionally with recursion).
#  * `list_memories`: Lists memories in Serena's project-specific memory store.
#  * `onboarding`: Performs onboarding (identifying the project structure and essential tasks, e.g. for testing or building).
#  * `prepare_for_new_conversation`: Provides instructions for preparing for a new conversation (in order to continue with the necessary context).
#  * `read_file`: Reads a file within the project directory.
#  * `read_memory`: Reads the memory with the given name from Serena's project-specific memory store.
#  * `remove_project`: Removes a project from the Serena configuration.
#  * `replace_lines`: Replaces a range of lines within a file with new content.
#  * `replace_symbol_body`: Replaces the full definition of a symbol.
#  * `restart_language_server`: Restarts the language server, may be necessary when edits not through Serena happen.
#  * `search_for_pattern`: Performs a search for a pattern in the project.
#  * `summarize_changes`: Provides instructions for summarizing the changes made to the codebase.
#  * `switch_modes`: Activates modes by providing a list of their names
#  * `think_about_collected_information`: Thinking tool for pondering the completeness of collected information.
#  * `think_about_task_adherence`: Thinking tool for determining whether the agent is still on track with the current task.
#  * `think_about_whether_you_are_done`: Thinking tool for determining whether the task is truly completed.
#  * `write_memory`: Writes a named memory (for future reference) to Serena's project-specific memory store.
excluded_tools: []

# list of tools to include that would otherwise be disabled (particularly optional tools that are disabled by default)
included_optional_tools: []

# Project context for AI assistants
initial_prompt: |
  # PinGlass (AI Photo Portraits)

  ## Overview
  Next.js 16 web application for generating AI photo portraits using Google Imagen 3.0.
  Users upload 10-20 reference photos, select a pricing tier (7/15/23 photos), pay, and receive AI-generated portraits.

  ## Tech Stack
  - Frontend: React 19, Next.js 16 (App Router), TypeScript
  - Styling: Tailwind CSS 4 with OKLCH color space
  - Database: Neon PostgreSQL (serverless)
  - AI: Google Imagen 3.0 API (via YeScale proxy)
  - Payments: T-Bank (Tinkoff) Payment API

  ## Pricing Tiers
  - Starter: 7 photos - 499 RUB
  - Standard: 15 photos - 999 RUB (popular)
  - Premium: 23 photos - 1499 RUB

  ## Key Files (with line counts)
  - `components/persona-app.tsx` (414 lines) - Main component, all views and state
  - `components/payment-modal.tsx` (323 lines) - Payment UI with tier selection
  - `lib/imagen.ts` (521 lines) - Google Imagen API wrapper
  - `lib/prompts.ts` (103 lines) - 23 generation prompts + style configs
  - `lib/tbank.ts` (240 lines) - T-Bank payment integration
  - `lib/db.ts` (63 lines) - Database client and TypeScript types
  - `app/api/generate/route.ts` (264 lines) - Photo generation endpoint
  - `app/api/payment/create/route.ts` (73 lines) - Payment creation
  - `app/api/payment/status/route.ts` (88 lines) - Payment status check
  - `app/api/payment/webhook/route.ts` (58 lines) - T-Bank webhooks

  ## Component Views (in persona-app.tsx)
  - OnboardingView (lines 154-226) - Animated welcome with orbiting photos
  - DashboardView (lines 228-280) - Avatar gallery with pricing tiers
  - UploadView (lines 282-328) - Multi-file upload (10-20 photos)
  - TierSelectView (lines 331-364) - Select 7/15/23 photo package
  - GeneratingView (lines 138-152) - Progress indicator
  - ResultsView (lines 366-414) - Generated photos gallery

  ## User Flow
  1. Onboarding (animated intro) -> 2. Upload (10-20 photos)
  3. Select tier (7/15/23 photos) -> 4. Payment (T-Bank)
  5. Generation (AI photos) -> 6. Results gallery (download)

  ## Database Tables
  - users (device_id, telegram_user_id) - payment status from payments table
  - avatars (user_id, name, status, thumbnail_url)
  - generated_photos (avatar_id, style_id, prompt, image_url)
  - payments (user_id, payment_id, amount, status)
  - generation_jobs (avatar_id, style_id, status, progress)

  ## Styles (in lib/prompts.ts)
  - PinGlass: All 23 prompts, optimistic vibrant portraits
  - Professional: 9 prompts for business/LinkedIn
  - Lifestyle: 9 prompts for social media
  - Creative: 9 prompts for artistic portfolio
# Source file patterns for indexing
source_patterns:
- "app/**/*.ts"
- "app/**/*.tsx"
- "components/**/*.tsx"
- "lib/**/*.ts"
- "styles/**/*.css"
- "*.json"
- "*.mjs"
- "*.js"
- "*.md"

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []
